# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-08 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0002_auto_20170907_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example',
            name='link',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='example',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='meaning',
            name='meaning',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='meaning',
            name='ontologyToken',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='valenceframe',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='valenceframe',
            name='name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
