# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0003_auto_20170908_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meaning',
            name='meaning',
            field=models.CharField(blank=True, default='', max_length=511),
        ),
    ]
