# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0004_auto_20170918_0455'),
    ]

    operations = [
        migrations.AddField(
            model_name='valenceframe',
            name='type',
            field=models.CharField(choices=[('sas', 'SAS'), ('fct', 'FCT')], default='sas', max_length=8),
            preserve_default=False,
        ),
    ]
