# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 06:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0006_remove_valenceframe_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meaningvalence',
            name='valenceFrame',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examples', to='lexicon.ValenceFrame'),
        ),
    ]
