# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0010_auto_20170928_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='meaning',
            name='relatedMeanings',
            field=models.ManyToManyField(blank=True, related_name='_meaning_relatedMeanings_+', to='lexicon.Meaning'),
        ),
    ]
